name: ClickDetection
version: 1.0.2
main: Ignacio\ClickDetection\Main
api: 3.15.4
depend:
  - PreciseCpsCounter

permissions:
  cps.watch:
    default: op
    description: Sends a message to all people with op by default or with the permission how fast someone is clicking.
